name: Cron

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *"

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: "debug"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up cargo cache
      uses: actions/cache@v3
      continue-on-error: false
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-
    - name: Run
      run: cargo run
      env:
        TELOXIDE_TOKEN: ${{ secrets.TELOXIDE_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        WEEK_DELTA_THRESHOLD: 5
        DAY_DELTA_THRESHOLD: 3
        WATCHED_STOCKS: GOOG,MSFT,META,NFLX,SCHG,TQQQ,MS,GS,MCO,SPGI,AMZN,JPM,NVDA,MA,TSLA,FICO
