name: Cron

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *"

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: "debug"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run
      run: cargo run
      env:
        TELOXIDE_TOKEN: ${{ secrets.TELOXIDE_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        WEEK_DELTA_THRESHOLD: -100
        DAY_DELTA_THRESHOLD: -100
        WATCHED_STOCKS: GOOG,MSFT,META,NFLX,SCHG,TQQQ,MS,GS,MCO,SPGI,AMZN,JPM,NVDA,MA,TSLA
