name: Cron

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * 1-5"

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: "debug"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up cargo cache
      uses: actions/cache@v3
      continue-on-error: false
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Run
      run: cargo run
      env:
        TELOXIDE_TOKEN: ${{ secrets.TELOXIDE_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        WEEK_DELTA_THRESHOLD: 5
        DAY_DELTA_THRESHOLD: 3
        WATCHED_STOCKS: MSFT,NVDA,AAPL,AMZN,GOOG,GOOGL,META,TSLA,AVGO,BRK-B,WMT,JPM,V,LLY,MA,NFLX,ORCL,COST,XOM,PG,JNJ,HD,BAC,ABBV,KO,PLTR,PM,TMUS,UNH,CRM,GE,CSCO,WFC,CVX,IBM,ABT,MCD,LIN,NOW,INTU,AXP,MS,DIS,ISRG,T,ACN,MRK,UBER,AMD,VZ,PEP,GS,BKNG,RTX,ADBE,BX,TXN,CAT,PGR,QCOM,SCHW,SPGI,BSX,BA,TMO,BLK,AMGN,SYK,HON,TJX,C,NEE,DE,DHR,GILD,UNP,PFE,ADP,GEV,AMAT,CMCSA,ETN,LOW,PANW,ANET,CRWD,CB,VRTX,MMC,LMT,LRCX,MU,KKR,COP,ADI,APH,MDT,KLAC,CME,ICE,PLD,MO,AMT,WELL,SBUX,SO,TT,CEG,WM,BMY,HCA,NKE,CTAS,MCK,INTC,SHW,DUK,DASH,FI,AJG,MCO,MDLZ,ELV,EQIX,PH,CDNS,CI,UPS,TDG,FTNT,MMM,ABNB,RSG,CVS,AON,DELL,ORLY,SNPS,APO,CL,ECL,GD,ZTS,WMB,COF,MAR,ITW,MSI,PYPL,PNC,HWM,RCL,NOC,CMG,USB,EMR,JCI,COIN,ADSK,BK,WDAY,REGN,CHTR,AZO,MNST,KMI,TRV,ROP,CARR,APD,SPG,EOG,HLT,CSX,AXON,NEM,DLR,PAYX,COR,FCX,AFL,NSC,VST,ALL,AEP,PSA,MET,GWW,FDX,TFC,SRE,OKE,O,CPRT,PWR,NXPI,BDX,PCAR,MPC,AMP,AIG,CTVA,TEL,FAST,D,NDAQ,KMB,GM,URI,PSX,ROST,SLB,LHX,EW,KVUE,KR,CMI,KDP,VRSK,TGT,MSCI,EXC,CCI,GLW,FIS,TTWO,AME,IDXX,OXY,HES,F,VLO,FANG,YUM,XEL,CTSH,FICO,GRMN,PEG,LULU,OTIS,PCG,ED,HIG,EA,PRU,CAH,BKR,DHI,CBRE,RMD,ROK,ETR,SYY,ACGL,VMC,TRGP,ODFL,WAB,DXCM,IT,WEC,EBAY,EQT,VICI,MLM,IR,EXR,MPWR,LYV,GEHC,EFX,STZ,BRO,DAL,HSY,A,KHC,CSGP,TKO,MCHP,WTW,XYL,NRG,ANSS,CCL,RJF,GIS,MTB,VTR,LVS,AVB,IRM,DD,K,TPL,BR,CNC,DTE,WRB,SCHG,TQQQ
